import React from 'react';
import { AlertTriangle } from 'lucide-react';
import Card from '../common/Card';

const PrescriptionViewer = () => {
  return (
    <Card hover={false} className="bg-amber-50 dark:bg-amber-900/20 border-amber-200 dark:border-amber-800 mt-4">
      <div className="flex items-start gap-3">
        <AlertTriangle size={20} className="text-amber-500 flex-shrink-0 mt-0.5" />
        <div>
          <h4 className="text-sm font-semibold text-amber-700 dark:text-amber-400">Medical Disclaimer</h4>
          <p className="text-xs text-amber-600 dark:text-amber-300 mt-1 leading-relaxed">
            This AI-powered analysis is for informational purposes only and does not constitute medical advice, diagnosis, or treatment. 
            Always consult a qualified healthcare professional for medical decisions. The results shown are generated by AI and may not be 100% accurate.
          </p>
        </div>
      </div>
    </Card>
  );
};

export default PrescriptionViewer;
